sections:
  - id: exec       # A
    index: A
    title: The AI/ML Brief
    description: The 2–3 most consequential items this week.
    match:
      sources: ["MIT Technology Review (AI)","Harvard Business Review (AI)","McKinsey (All)","Gartner Blog (All)"]
      domains: []
      keywords: ["policy","regulation","roadmap","strategy","leadership","CIO","CISO","budget","investment","risk"]

  - id: strategy   # B
    index: B
    title: Strategy & Market Analysis
    description: Funding, competitive moves, adoption trends, business models.
    match:
      sources: ["VentureBeat (AI)","TechCrunch (AI)","MIT Technology Review (AI)","Harvard Business Review (AI)","McKinsey (All)","Gartner Blog (All)"]
      domains: ["technologyreview.com","hbr.org","venturebeat.com","techcrunch.com","mckinsey.com","gartner.com"]
      keywords: ["market","funding","valuation","adoption","TCO","ROI","partnership","M&A","ecosystem"]

  - id: launches   # C
    index: C
    title: Launches & Product Updates
    description: Vendor releases, pricing, GA announcements, integrations.
    match:
      sources: ["OpenAI News","Google AI Blog","NVIDIA Blog","AWS Machine Learning Blog"]
      domains: ["openai.com","blog.google","blogs.nvidia.com","aws.amazon.com"]
      keywords: ["launch","shipping","GA","general availability","pricing","preview","integration","SDK","release"]

  - id: security   # D
    index: D
    title: Security, Safety & Governance
    description: Risks, mitigations, evals, incidents, compliance.
    match:
      sources: ["VentureBeat (AI)","TechCrunch (AI)","MIT Technology Review (AI)"]
      domains: []
      keywords: ["security","safety","governance","audit","prompt injection","exfiltration","jailbreak","abuse","PII","policy"]

  - id: applied    # E
    index: E
    title: Applied Engineering & Case Studies
    description: Practical builds, RAG patterns, reference templates.
    match:
      sources: ["AWS Machine Learning Blog","Google AI Blog","VentureBeat (AI)","TechCrunch (AI)"]
      domains: ["medium.com","dev.to","github.com","aws.amazon.com","blog.google"]
      keywords: ["RAG","case study","playbook","reference","implementation","how we built","template","solution","architecture"]

  - id: infra      # F
    index: F
    title: Infrastructure & Performance
    description: Serving, inference, KV, quantization, throughput/latency.
    match:
      sources: ["NVIDIA Blog","AWS Machine Learning Blog","Google AI Blog"]
      domains: ["blogs.nvidia.com","pytorch.org","tensorflow.org","developer.nvidia.com","aws.amazon.com","blog.google"]
      keywords: ["throughput","latency","KV cache","Triton","CUDA","vLLM","quantization","LoRA","TensorRT","A100","H100","performance","scaling"]

  - id: research   # G
    index: G
    title: Foundational Research & Emerging Trends
    description: Research papers, breakthroughs, and emerging AI trends for business leaders.
    match:
      sources: ["Google AI Blog","Distill Research","Google DeepMind","NVIDIA AI Research","AWS Machine Learning Blog","arXiv AI Papers","arXiv Machine Learning Papers","arXiv NLP Papers","arXiv Computer Vision Papers","MIT Technology Review (AI)","VentureBeat (AI)"]
      domains: ["blog.google","distill.pub","blogs.nvidia.com","aws.amazon.com","arxiv.org","technologyreview.com","venturebeat.com"]
      keywords: ["research","paper","novel","breakthrough","sota","benchmark","dataset","theory","scaling law","transformer","federated","responsible AI","study","analysis","trends","machine learning","deep learning","large language model","llm","neural","reinforcement learning","natural language processing","nlp"]

order: [exec, strategy, launches, security, applied, infra, research]

