sources:
  - { name: "arXiv cs.LG", type: rss, url: "https://export.arxiv.org/rss/cs.LG" }
  - { name: "arXiv cs.CL", type: rss, url: "https://export.arxiv.org/rss/cs.CL" }
  - { name: "OpenAI Blog", type: rss, url: "https://openai.com/blog/rss.xml" }
  - { name: "Google AI Blog", type: rss, url: "https://ai.googleblog.com/feeds/posts/default" }
  - { name: "Anthropic", type: rss, url: "https://www.anthropic.com/news.xml" }
  - { name: "Hugging Face", type: rss, url: "https://huggingface.co/blog/rss.xml" }
  - { name: "Meta AI", type: rss, url: "https://ai.facebook.com/blog/rss/" }
