sources:
  # Research & Academic (working alternatives to broken arXiv feeds)
  - name: "Google AI Blog"
    type: rss
    url: "https://blog.google/technology/ai/rss/"
    include_keywords: ["research", "paper", "novel", "breakthrough", "sota", "machine learning", "deep learning"]
    max_items: 15
  - name: "Distill Research"
    type: rss
    url: "https://distill.pub/rss.xml"
    include_keywords: ["research", "paper", "novel", "breakthrough", "sota", "machine learning", "deep learning"]
    max_items: 15
  - name: "Google DeepMind"
    type: rss
    url: "https://blog.google/technology/google-deepmind/rss/"
    include_keywords: ["research", "paper", "novel", "breakthrough", "sota", "machine learning", "deep learning"]
    max_items: 15
  - name: "NVIDIA AI Research"
    type: rss
    url: "https://blogs.nvidia.com/feed/"
    include_keywords: ["research", "paper", "novel", "breakthrough", "sota", "machine learning", "deep learning", "ai"]
    max_items: 15
  - name: "AWS Machine Learning Blog"
    type: rss
    url: "https://aws.amazon.com/blogs/machine-learning/feed/"
    include_keywords: ["research", "paper", "novel", "breakthrough", "sota", "machine learning", "deep learning", "ai"]
    max_items: 15
  # arXiv Research Papers (AI/ML/LLM focused)
  - name: "arXiv AI Papers"
    type: rss
    url: "https://rss.arxiv.org/rss/cs.AI"
    include_keywords: ["large language model", "llm", "transformer", "neural", "deep learning", "machine learning", "artificial intelligence", "reinforcement learning", "natural language processing", "nlp"]
    max_items: 20
  - name: "arXiv Machine Learning Papers"
    type: rss
    url: "https://rss.arxiv.org/rss/cs.LG"
    include_keywords: ["large language model", "llm", "transformer", "neural", "deep learning", "machine learning", "artificial intelligence", "reinforcement learning", "natural language processing", "nlp"]
    max_items: 20
  - name: "arXiv NLP Papers"
    type: rss
    url: "https://rss.arxiv.org/rss/cs.CL"
    include_keywords: ["large language model", "llm", "transformer", "neural", "deep learning", "machine learning", "artificial intelligence", "reinforcement learning", "natural language processing", "nlp"]
    max_items: 20
  - name: "arXiv Computer Vision Papers"
    type: rss
    url: "https://rss.arxiv.org/rss/cs.CV"
    include_keywords: ["large language model", "llm", "transformer", "neural", "deep learning", "machine learning", "artificial intelligence", "computer vision", "image", "video"]
    max_items: 15

  # Strategic & Business Impact
  - { name: "MIT Technology Review (AI)", type: rss, url: "https://www.technologyreview.com/topic/artificial-intelligence/feed/" }
  - { name: "Harvard Business Review (AI)", type: rss, url: "https://hbr.org/rss/topic/artificial-intelligence" }
  - { name: "VentureBeat (AI)", type: rss, url: "https://venturebeat.com/category/ai/feed/" }
  - name: McKinsey (All)
    type: rss
    url: https://www.mckinsey.com/rss
    include_keywords: ["ai","artificial intelligence","machine learning","ml","gen ai","generative ai"]
  - { name: "TechCrunch (AI)", type: rss, url: "https://techcrunch.com/category/artificial-intelligence/feed/" }
  - name: Gartner Blog (All)
    type: rss
    url: https://www.gartner.com/en/blog/feed
    include_keywords: ["ai","artificial intelligence","machine learning","ml","gen ai","generative ai"]

  # Platforms & Enterprise Ops
  - { name: "AWS Machine Learning Blog", type: rss, url: "https://aws.amazon.com/blogs/machine-learning/feed/" }
  - { name: "Google AI Blog",            type: rss, url: "https://ai.googleblog.com/feeds/posts/default" }
  - { name: "NVIDIA Blog",               type: rss, url: "https://blogs.nvidia.com/feed/" }
  - { name: "OpenAI News",               type: rss, url: "https://openai.com/news/rss.xml" }
