name: Publish Newsletter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build static issue (collect → score → render)
      run: |
        set -euxo pipefail
        python app/collector/rss_collect.py
        wc -l data/candidates.jsonl || true
        python app/scorer/score.py
        cat data/top10.json || true
        python app/build_issue.py
        ls -la site/dist
        sed -n '1,60p' site/dist/index.html
        test -f site/dist/index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/dist
